### PR TITLE
Fix ssh cloned git url not matched

### LINKED ISSUE #6: codedoc check fails on ssh cloned repos
Codedoc check gives me this error, although my repo is setup correctly in the `config.ts`

```
# Checking GitHub configuration ...
#
# WARNING::
# Your CODEDOC config indicates GitHub integration, but
# your project folder is not in sync with a GitHub repository.
#
# You can fix this by modifying .codedoc/config.ts
#
# Read https://codedoc.cc/docs/config/misc#github-integration for more information.
#
```

I looked up into your utils github info file and it seems the regex provided is not respecting any repositories cloned with ssh. The url changes here for ssh cloned repositories in this format (e.g. for me): `git@github.com:uloco/uloco.coding.blog.git`

### PR DESCRIPTION
**Pull request by uloco**
Fixes #6

### CODE REVIEW

**Comment by uloco** [comment]
Tested here https://regexr.com/5dfqa

**Comment by loreanvictor** [comment]
the proposed regex also captures `.git` as part of the repo name, which conflicts with how already existing repos and other github integrations operate (as they assume the repo name does not include `.git`). I suspect having the `.git` as _required_ doesn't do any harm (since both cloning via https and ssh from github you will have the `.git` as the origin address on your cloned folder).

@uloco could you please revert that bit so I can merge your PR? I could fix that manually and add this fix via another commit, but it is better if contribution history is kept properly.

**Comment by uloco** [comment]
Sure. There was already a git suffix in your regex before, so I thought I fixed an issue by making it optional. Too much regex magic for me I guess :D

**Comment by loreanvictor** [comment]
> Sure. There was already a git suffix in your regex before, so I thought I fixed an issue by making it optional. Too much regex magic for me I guess :D

yeah it also took me some head-scratching to realize why it was being captured (making the suffix optional simply allows `repo` capture group to include the suffix without invalidating the match).

**Comment by loreanvictor** [comment]
published via `@codedoc/cli@0.2.6` (you can update by running `codedoc update`). thanks a lot @uloco !

**Pull request merged**
